---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: doctoc
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: actionlint
      - id: markdownlint
      - id: yamllint
