---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: "v0.34.0"
    hooks:
      - id: markdownlint
        args: ["-f"]
        stages: [commit]
  - repo: https://github.com/thlorenz/doctoc
    rev: v1.4.0
    hooks:
      - id: doctoc
  - repo: https://github.com/adrienverge/yamllint.git
    sha: v1.10.0
    hooks:
      - id: yamllint
